##############################################################
##############################################################
# This is an example configuration provided by Wraith.
# Feel free to amend for your own requirements.
# ---
# This particular config is intended to demonstrate how
# to use Wraith in 'history' mode, which is best suited to
# making sure your site's appearance remains consistent over
# time.
#
# `wraith history history.yaml` # generate base screenshots
# `wraith latest history.yaml`  # take new shots and compare
#
##############################################################
##############################################################

# (required) The engine to run Wraith with. Examples: 'phantomjs', 'casperjs', 'slimerjs'
browser: "casperjs"

# (required) The domain to take screenshots of.
domains:
  modules: "http://dev-bampfa-site.pantheon.berkeley.edu"

# (required) The paths to capture. This particular config is using casperjs, so we can take screenshots of selectors rather than the entire page.
paths:
  home:       /
  fourohfour: /404
  fourohfourtwo: /404-page-not-found
  about: /about
  abouttwo: /about/about-bampfa
  aboutthree: /about/about-bampfa/architecture
  aboutfour: /about/faqs
  contact: /contact
  educator: /educators-researchers
  families: /families
  meet: /meet
  calendarweek: 
    path: /visit/calendar/week?date=2017-W08
    before_capture: 'javascript/calendarweektab--casper.js'
  calendar: /visit/calendar?date=2017-02
  calendarmodal:
    path: /visit/calendar?date=2017-02
    before_capture: 'javascript/calendarmodal--casper.js' 
  calendarfilter:  
    path: /visit/calendar?date=2017-02
    before_capture: 'javascript/calendarfilter--casper.js' 
  onview: 
    path: /on-view?field_event_series_type_value=1&field_dates_value=2&field_dates_value2=2
    before_capture: 'javascript/onviewfilter--casper.js' 
  members: /members
  past_exhibition: /page/past-exhibitions
  students: /students
  support: /support
  make_gift: /support/make-gift
  visit: /visit
  precededby: /event/sorrows-struggle
  doublefeature: /event/white-zombie-crime-doctor-crespi
  multipleshowtimes: /event/last-days-city
  followedby: /event/blockade-1
  shorts: /event/clock-notions-cinematic-temporality
  blockquote: /event/kalpana
  filmseries: /program/not-reconciled-cinema-straub-huillet
  exhibition: program/hippie-modernism-struggle-utopia
  pressroom: /press
  pressrelease: /press/michael-armitage-matrix-263
  news: /news
  newsingle: /news/filmmaker-jem-cohen-deliver-2017-les-blank-lecture
  search: /search/hitchcock
  todaysevents: /signage/todays-events
  theaterslideshow: /signage/theater-slideshow
  signageoveriew: /signage/overview
  todaysevents: /signage/todays-events
  todaysfilms: /signage/todays-films
  outdoorslideshow: /signage/outdoor-slideshow
  wfu: /email/weekly-film-update
  programguides: /program-guides

# (optional) JavaScript file to execute before taking screenshot of every path. Default: nil
before_capture: 'javascript/wait--casper.js'

# (required) Screen widths (and optional height) to resize the browser to before taking the screenshot.
screen_widths:
  - 320x10000
  - 800x10000
  - 1280x10000

# (optional) Resize to each screen width (efficient), or reload at each screen width (costly). Default: 'reload'
resize_or_reload: 'resize'

# (required for history mode, otherwise optional) The directory that your base screenshots will be stored in.
history_dir: 'shots_base'

# (required) The directory that your latest screenshots will be stored in
directory: 'shots'

# (required) Amount of fuzz ImageMagick will use when comparing images. A higher fuzz makes the comparison less strict.
fuzz: '20%'

# (optional) The maximum acceptable level of difference (in %) between two images before Wraith reports a failure. Default: 0
threshold: 5

# (optional) Specify the template (and generated thumbnail sizes) for the gallery output.
gallery:
  template: 'slideshow_template' # Examples: 'basic_template' (default), 'slideshow_template'
  thumb_width:  200
  thumb_height: 200

# (optional) Choose which results are displayed in the gallery, and in what order. Default: alphanumeric
# Options:
#   alphanumeric - all paths (with or without a difference) are shown, sorted by path
#   diffs_first - all paths (with or without a difference) are shown, sorted by difference size (largest first)
#   diffs_only - only paths with a difference are shown, sorted by difference size (largest first)
# Note: different screen widths are always grouped together.
mode: diffs_first

# (optional) Choose to run Wraith in verbose mode, for easier debugging. Default: false
# verbose: true

# (optional) Color to highlight the image diff. Default: 'blue'
highlight_color: red

# (optional) Parameters to pass to Phantom/Casper command line. Default: '--ignore-ssl-errors=true --ssl-protocol=tlsv1'
phantomjs_options: ''
